/// Open CRM pipeline at 30 June 2026, weighted and unweighted. Page 3.
table Pipeline
	lineageTag: eb3b2aa5-fa18-51ba-bb80-472722ebfc8b

	/// Unweighted open pipeline at the reporting date, all deal types.
	measure 'Open Pipeline ACV' =
			SUM('Pipeline'[ACV])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: 03 GTM
		lineageTag: 72523507-83e6-5d4e-9fdf-599a132499fe

	/// Open pipeline weighted by stage probability. Neither view is assumed more accurate; both are
	/// reported (PHASE1_SPEC 8.9).
	measure 'Weighted Pipeline ACV' =
			SUM('Pipeline'[Weighted ACV])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: 03 GTM
		lineageTag: 1ada3d17-d6ab-5bb6-a84c-8ff85225687a

	/// Unweighted open New Logo pipeline only.
	measure 'Open New Logo Pipeline ACV' =
			CALCULATE(SUM('Pipeline'[ACV]), 'Pipeline'[Deal Type] = "New Logo")
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: 03 GTM
		lineageTag: 2e4b799c-436e-51a2-be31-52090a6f54fc

	column Segment
		dataType: string
		isHidden
		lineageTag: 6b547882-227b-5ea0-b34b-8f9df64984e5
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column 'Expected Close Month'
		dataType: dateTime
		isHidden
		formatString: yyyy-mm-dd
		lineageTag: 598081c8-1763-5d4b-bd95-61a77712baac
		summarizeBy: none
		sourceColumn: Expected Close Month

		annotation SummarizationSetBy = Automatic

	column Stage
		dataType: string
		lineageTag: 735472d9-3de6-5ab5-9e81-6caba1c3816f
		summarizeBy: none
		sourceColumn: Stage

		annotation SummarizationSetBy = Automatic

	column 'Deal Type'
		dataType: string
		lineageTag: 5a2efe2f-f038-532d-a433-21dbc89153dc
		summarizeBy: none
		sourceColumn: Deal Type

		annotation SummarizationSetBy = Automatic

	column ACV
		dataType: double
		isHidden
		formatString: \$#,##0;(\$#,##0);\$0
		lineageTag: 0ab63a85-f916-5f81-9624-8e5db40a76a0
		summarizeBy: none
		sourceColumn: ACV

		annotation SummarizationSetBy = Automatic

	column 'Weighted ACV'
		dataType: double
		isHidden
		formatString: \$#,##0;(\$#,##0);\$0
		lineageTag: 091b304c-a648-5b6b-9433-dbb296e987d2
		summarizeBy: none
		sourceColumn: Weighted ACV

		annotation SummarizationSetBy = Automatic

	partition Pipeline = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(RepoRoot & "/data/marts/fct_pipeline_snapshot.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Kept = Table.SelectColumns(Headers, {"segment", "expected_close_month", "stage", "deal_type", "acv", "weighted_acv"}),
				    Typed = Table.TransformColumnTypes(Kept, {{"segment", type text}, {"expected_close_month", type date}, {"stage", type text}, {"deal_type", type text}, {"acv", type number}, {"weighted_acv", type number}}),
				    Renamed = Table.RenameColumns(Typed, {{"segment", "Segment"}, {"expected_close_month", "Expected Close Month"}, {"stage", "Stage"}, {"deal_type", "Deal Type"}, {"acv", "ACV"}, {"weighted_acv", "Weighted ACV"}})
				in
				    Renamed

	annotation PBI_ResultType = Table
